name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Extract version from tag
      id: tag_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/buchungsport:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/buchungsport:${{ steps.tag_version.outputs.VERSION }}

    - name: Log out of Docker Hub
      run: docker logout
